services:
  client:
    image: oven/bun:1.1-slim
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - ../../temp:/app/public/temp:ro
    working_dir: /app
    environment:
      - NODE_ENV=development
      - NEXT_TELEMETRY_DISABLED=1
      - HOSTNAME=0.0.0.0
    env_file:
      - .env.local
    extra_hosts:
      - "host.docker.internal:host-gateway"
    stdin_open: true
    tty: true
    command: ["sh", "-c", "./scripts/setup.sh && bun run dev --hostname 0.0.0.0"]
