"""Mock data for feed monitoring - based on collected data."""

from typing import List
from .schema import Post, FeedList, Subreddit, FeedStats

# Mock data based on actual collected posts
MOCK_POSTS_BROOKE_MONK_THE_SECOND = [
    Post(
        id="anc6w05ekr8g1",
        title="Brooke monk",
        created_utc="2025-12-22T08:14:39Z",
        score=7,
        num_comments=1,
        upvote_ratio=1.00,
        over_18=False,
        url="https://i.redd.it/anc6w05ekr8g1.jpeg",
        selftext="",
        permalink="/r/BrookeMonkTheSecond/comments/anc6w05ekr8g1/brooke_monk/",
        subreddit="BrookeMonkTheSecond",
        author="letsgoon45",
        is_image=True,
        image_url="https://i.redd.it/anc6w05ekr8g1.jpeg",
    ),
    Post(
        id="j8dewwyngr8g1",
        title="Brooke Monk blue dress",
        created_utc="2025-12-22T07:56:12Z",
        score=42,
        num_comments=1,
        upvote_ratio=1.00,
        over_18=False,
        url="https://i.redd.it/j8dewwyngr8g1.gif",
        selftext="",
        permalink="/r/BrookeMonkTheSecond/comments/j8dewwyngr8g1/brooke_monk_blue_dress/",
        subreddit="BrookeMonkTheSecond",
        author="MilkLover69_",
        is_image=True,
        image_url="https://i.redd.it/j8dewwyngr8g1.gif",
    ),
    Post(
        id="8cdnlyia4r8g1",
        title="Brooke monk",
        created_utc="2025-12-22T06:44:24Z",
        score=4,
        num_comments=2,
        upvote_ratio=0.70,
        over_18=False,
        url="https://i.redd.it/8cdnlyia4r8g1.jpeg",
        selftext="",
        permalink="/r/BrookeMonkTheSecond/comments/8cdnlyia4r8g1/brooke_monk/",
        subreddit="BrookeMonkTheSecond",
        author="Ok_Figure9249",
        is_image=True,
        image_url="https://i.redd.it/8cdnlyia4r8g1.jpeg",
    ),
    Post(
        id="lrv8qklgeo8g1",
        title="Brooke Monk",
        created_utc="2025-12-21T21:36:03Z",
        score=0,
        num_comments=4,
        upvote_ratio=0.36,
        over_18=False,
        url="https://i.redd.it/lrv8qklgeo8g1.jpeg",
        selftext="",
        permalink="/r/BrookeMonkTheSecond/comments/lrv8qklgeo8g1/brooke_monk/",
        subreddit="BrookeMonkTheSecond",
        author="NoFold9963",
        is_image=True,
        image_url="https://i.redd.it/lrv8qklgeo8g1.jpeg",
    ),
    Post(
        id="p1whj2sq5n8g1",
        title="Brooke Monk 🤍🖤",
        created_utc="2025-12-21T17:25:25Z",
        score=87,
        num_comments=1,
        upvote_ratio=0.98,
        over_18=False,
        url="https://i.redd.it/p1whj2sq5n8g1.jpeg",
        selftext="",
        permalink="/r/BrookeMonkTheSecond/comments/p1whj2sq5n8g1/brooke_monk/",
        subreddit="BrookeMonkTheSecond",
        author=None,
        is_image=True,
        image_url="https://i.redd.it/p1whj2sq5n8g1.jpeg",
    ),
    Post(
        id="sx9zz540am8g1",
        title="Including Brooke Monk",
        created_utc="2025-12-21T14:27:30Z",
        score=18,
        num_comments=8,
        upvote_ratio=0.83,
        over_18=False,
        url="https://i.redd.it/sx9zz540am8g1.jpeg",
        selftext="",
        permalink="/r/BrookeMonkTheSecond/comments/sx9zz540am8g1/including_brooke_monk/",
        subreddit="BrookeMonkTheSecond",
        author="Free-Worldliness1731",
        is_image=True,
        image_url="https://i.redd.it/sx9zz540am8g1.jpeg",
    ),
    Post(
        id="exbyice5ql8g1",
        title="Brooke Monk 💙",
        created_utc="2025-12-21T12:36:14Z",
        score=83,
        num_comments=2,
        upvote_ratio=0.98,
        over_18=False,
        url="https://i.redd.it/exbyice5ql8g1.jpeg",
        selftext="",
        permalink="/r/BrookeMonkTheSecond/comments/exbyice5ql8g1/brooke_monk/",
        subreddit="BrookeMonkTheSecond",
        author=None,
        is_image=True,
        image_url="https://i.redd.it/exbyice5ql8g1.jpeg",
    ),
    Post(
        id="am5jwtv7qg8g1",
        title="Brooke monk tease",
        created_utc="2025-12-20T19:47:42Z",
        score=249,
        num_comments=10,
        upvote_ratio=0.99,
        over_18=False,
        url="https://i.redd.it/am5jwtv7qg8g1.jpeg",
        selftext="",
        permalink="/r/BrookeMonkTheSecond/comments/am5jwtv7qg8g1/brooke_monk_tease/",
        subreddit="BrookeMonkTheSecond",
        author="OddEntertainer3333",
        is_image=True,
        image_url="https://i.redd.it/am5jwtv7qg8g1.jpeg",
    ),
    Post(
        id="1h1knkxosf8g1",
        title="Brooke Monk staring 🖤",
        created_utc="2025-12-20T16:39:54Z",
        score=152,
        num_comments=5,
        upvote_ratio=0.99,
        over_18=False,
        url="https://i.redd.it/1h1knkxosf8g1.jpeg",
        selftext="",
        permalink="/r/BrookeMonkTheSecond/comments/1h1knkxosf8g1/brooke_monk_staring/",
        subreddit="BrookeMonkTheSecond",
        author=None,
        is_image=True,
        image_url="https://i.redd.it/1h1knkxosf8g1.jpeg",
    ),
    Post(
        id="zvphb1sl2e8g1",
        title="Brooke Monk 💚🤍",
        created_utc="2025-12-20T10:51:47Z",
        score=208,
        num_comments=6,
        upvote_ratio=1.00,
        over_18=False,
        url="https://i.redd.it/zvphb1sl2e8g1.jpeg",
        selftext="",
        permalink="/r/BrookeMonkTheSecond/comments/zvphb1sl2e8g1/brooke_monk/",
        subreddit="BrookeMonkTheSecond",
        author=None,
        is_image=True,
        image_url="https://i.redd.it/zvphb1sl2e8g1.jpeg",
    ),
]

MOCK_POSTS_BEST_OF_BROOKE_MONK = [
    Post(
        id="1ps2zz6",
        title="Brooke Monk pink",
        created_utc="2025-12-21T03:54:38Z",
        score=16,
        num_comments=2,
        upvote_ratio=0.92,
        over_18=False,
        url="https://www.reddit.com/gallery/1ps2zz6",
        selftext="",
        permalink="/r/BestOfBrookeMonk/comments/1ps2zz6/brooke_monk_pink/",
        subreddit="BestOfBrookeMonk",
        author="Born-Win-3564",
        is_image=True,
        image_url="https://www.reddit.com/gallery/1ps2zz6",
    ),
    Post(
        id="1prjgwn",
        title="Brooke Monk Face",
        created_utc="2025-12-20T11:16:35Z",
        score=15,
        num_comments=3,
        upvote_ratio=0.94,
        over_18=False,
        url="https://www.reddit.com/gallery/1prjgwn",
        selftext="",
        permalink="/r/BestOfBrookeMonk/comments/1prjgwn/brooke_monk_face/",
        subreddit="BestOfBrookeMonk",
        author="Born-Win-3564",
        is_image=True,
        image_url="https://www.reddit.com/gallery/1prjgwn",
    ),
    Post(
        id="1pqs1hz",
        title="Brooke Monk face",
        created_utc="2025-12-19T12:10:03Z",
        score=12,
        num_comments=0,
        upvote_ratio=0.94,
        over_18=False,
        url="https://www.reddit.com/gallery/1pqs1hz",
        selftext="",
        permalink="/r/BestOfBrookeMonk/comments/1pqs1hz/brooke_monk_face/",
        subreddit="BestOfBrookeMonk",
        author="Born-Win-3564",
        is_image=True,
        image_url="https://www.reddit.com/gallery/1pqs1hz",
    ),
    Post(
        id="1pqs1dr",
        title="Brooke Monk face",
        created_utc="2025-12-19T12:09:56Z",
        score=7,
        num_comments=0,
        upvote_ratio=1.00,
        over_18=False,
        url="https://www.reddit.com/gallery/1pqs1dr",
        selftext="",
        permalink="/r/BestOfBrookeMonk/comments/1pqs1dr/brooke_monk_face/",
        subreddit="BestOfBrookeMonk",
        author="Born-Win-3564",
        is_image=True,
        image_url="https://www.reddit.com/gallery/1pqs1dr",
    ),
    Post(
        id="1pqfq1b",
        title="Brooke Monk Bikini",
        created_utc="2025-12-19T02:09:29Z",
        score=18,
        num_comments=1,
        upvote_ratio=1.00,
        over_18=False,
        url="https://www.reddit.com/gallery/1pqfq1b",
        selftext="",
        permalink="/r/BestOfBrookeMonk/comments/1pqfq1b/brooke_monk_bikini/",
        subreddit="BestOfBrookeMonk",
        author="Born-Win-3564",
        is_image=True,
        image_url="https://www.reddit.com/gallery/1pqfq1b",
    ),
    Post(
        id="1poz1um",
        title="Brooke Monk Bikini",
        created_utc="2025-12-17T09:16:29Z",
        score=2,
        num_comments=1,
        upvote_ratio=1.00,
        over_18=False,
        url="https://www.reddit.com/gallery/1poz1um",
        selftext="",
        permalink="/r/BestOfBrookeMonk/comments/1poz1um/brooke_monk_bikini/",
        subreddit="BestOfBrookeMonk",
        author="Born-Win-3564",
        is_image=True,
        image_url="https://www.reddit.com/gallery/1poz1um",
    ),
    Post(
        id="1poyykm",
        title="Brooke Monk",
        created_utc="2025-12-17T09:11:27Z",
        score=11,
        num_comments=2,
        upvote_ratio=0.88,
        over_18=False,
        url="https://www.reddit.com/gallery/1poyykm",
        selftext="",
        permalink="/r/BestOfBrookeMonk/comments/1poyykm/brooke_monk/",
        subreddit="BestOfBrookeMonk",
        author="Born-Win-3564",
        is_image=True,
        image_url="https://www.reddit.com/gallery/1poyykm",
    ),
    Post(
        id="1pohhim",
        title="Brooke Monk the Goddess",
        created_utc="2025-12-16T17:46:44Z",
        score=7,
        num_comments=1,
        upvote_ratio=0.90,
        over_18=False,
        url="https://www.reddit.com/gallery/1pohhim",
        selftext="",
        permalink="/r/BestOfBrookeMonk/comments/1pohhim/brooke_monk_the_goddess/",
        subreddit="BestOfBrookeMonk",
        author="Born-Win-3564",
        is_image=True,
        image_url="https://www.reddit.com/gallery/1pohhim",
    ),
    Post(
        id="1pofc61",
        title="Brooke Monk",
        created_utc="2025-12-16T16:15:09Z",
        score=27,
        num_comments=8,
        upvote_ratio=0.95,
        over_18=False,
        url="https://www.reddit.com/gallery/1pofc61",
        selftext="",
        permalink="/r/BestOfBrookeMonk/comments/1pofc61/brooke_monk/",
        subreddit="BestOfBrookeMonk",
        author="Born-Win-3564",
        is_image=True,
        image_url="https://www.reddit.com/gallery/1pofc61",
    ),
    Post(
        id="1poetnt",
        title="Brooke Monk Bikini",
        created_utc="2025-12-16T16:08:24Z",
        score=9,
        num_comments=3,
        upvote_ratio=0.86,
        over_18=False,
        url="https://www.reddit.com/gallery/1poetnt",
        selftext="",
        permalink="/r/BestOfBrookeMonk/comments/1poetnt/brooke_monk_bikini/",
        subreddit="BestOfBrookeMonk",
        author="Born-Win-3564",
        is_image=True,
        image_url="https://www.reddit.com/gallery/1poetnt",
    ),
]

MOCK_FEED_LISTS = [
    FeedList(
        subreddit="BrookeMonkTheSecond",
        posts=MOCK_POSTS_BROOKE_MONK_THE_SECOND,
        total_count=10,
    ),
    FeedList(
        subreddit="BestOfBrookeMonk",
        posts=MOCK_POSTS_BEST_OF_BROOKE_MONK,
        total_count=10,
    ),
]

MOCK_SUBREDDITS = [
    Subreddit(name="BrookeMonkTheSecond", post_count=10),
    Subreddit(name="BestOfBrookeMonk", post_count=10),
]

MOCK_STATS = FeedStats(
    total_posts=20,
    total_subreddits=2,
    total_users=5,
    posts_today=3,
)

