"""
Metadata Extractor for ComfyUI PNG Images

Extracts prompt and workflow metadata from PNG image files generated by ComfyUI.
"""

import json
import re
from pathlib import Path
from typing import Dict, Any, Optional, List
from PIL import Image
from PIL.PngImagePlugin import PngInfo


class MetadataExtractor:
    """Extracts metadata from ComfyUI-generated PNG images."""

    def __init__(self):
        """Initialize the metadata extractor."""
        pass

    def extract_from_image(self, image_path: Path) -> Optional[Dict[str, Any]]:
        """
        Extract metadata from a PNG image file.

        Args:
            image_path: Path to the PNG image file

        Returns:
            Dictionary containing extracted metadata, or None if extraction fails
        """
        try:
            with Image.open(image_path) as img:
                # ComfyUI stores metadata in PNG text chunks (stored in img.info)
                metadata = {}
                
                # Extract PNG text chunks from info (Pillow stores them here)
                if img.info:
                    for key, value in img.info.items():
                        # PNG text chunks have keys starting with specific prefixes
                        # ComfyUI uses 'prompt' and 'workflow' as text chunk keys
                        if isinstance(value, str):
                            metadata[key] = value
                
                # Also check text attribute (older Pillow versions)
                if hasattr(img, 'text') and img.text:
                    metadata.update(img.text)
                
                # ComfyUI often stores workflow/prompt in specific chunks
                # Try to extract workflow JSON if present
                workflow_data = None
                prompt_data = None
                
                # Check for 'workflow' key
                if 'workflow' in metadata:
                    try:
                        workflow_data = json.loads(metadata['workflow'])
                    except (json.JSONDecodeError, TypeError):
                        pass
                
                # Check for 'prompt' key (ComfyUI stores prompt as JSON)
                if 'prompt' in metadata:
                    try:
                        prompt_data = json.loads(metadata['prompt'])
                    except (json.JSONDecodeError, TypeError):
                        prompt_data = metadata['prompt']  # Might be plain text
                
                # Also check for 'parameters' (some ComfyUI versions use this)
                if 'parameters' in metadata and not prompt_data:
                    try:
                        params = json.loads(metadata['parameters'])
                        if isinstance(params, dict):
                            prompt_data = params.get('Prompt', params.get('prompt'))
                    except (json.JSONDecodeError, TypeError):
                        pass
                
                # Also check EXIF data for ComfyUI-specific metadata
                if hasattr(img, '_getexif') and img._getexif():
                    exif = img._getexif()
                    # ComfyUI sometimes stores data in EXIF UserComment
                    for tag_id, value in exif.items():
                        if isinstance(value, str) and ('workflow' in value.lower() or 'prompt' in value.lower()):
                            try:
                                parsed = json.loads(value)
                                if isinstance(parsed, dict):
                                    metadata.update(parsed)
                            except (json.JSONDecodeError, TypeError):
                                pass
                
                # Return structured metadata
                result = {
                    'filename': image_path.name,
                    'filepath': str(image_path),
                    'workflow': workflow_data,
                    'prompt': prompt_data,
                    'raw_metadata': metadata
                }
                
                return result if (workflow_data or prompt_data or metadata) else None
                
        except Exception as e:
            return None

    def extract_from_directory(
        self, 
        directory: Path, 
        recursive: bool = False,
        pattern: str = "*.png"
    ) -> List[Dict[str, Any]]:
        """
        Extract metadata from all PNG files in a directory.

        Args:
            directory: Directory path to scan
            recursive: Whether to scan subdirectories recursively
            pattern: File pattern to match (default: "*.png")

        Returns:
            List of metadata dictionaries (excluding failed extractions)
        """
        directory = Path(directory)
        
        if not directory.exists():
            raise FileNotFoundError(f"Directory does not exist: {directory}")
        
        if not directory.is_dir():
            raise NotADirectoryError(f"Path is not a directory: {directory}")
        
        results = []
        
        if recursive:
            image_files = list(directory.rglob(pattern))
        else:
            image_files = list(directory.glob(pattern))
        
        if not image_files:
            return results
        
        for image_path in image_files:
            metadata = self.extract_from_image(image_path)
            if metadata:
                results.append(metadata)
        
        return results

