import os
import polars as pl
from typing import List, Dict, Any, Optional
from datetime import datetime
from io import BytesIO

# Assuming the runtime environment can resolve these imports
from crawling_system.storage.minio_store import MinioStore
from src.feed.storage.neo4j_connection import get_connection as get_neo4j_connection

# Configuration
DATASET_BUCKET = "datasets"
NEO4J_DATABASE = "neo4j"
BATCH_SIZE = 1000

def run_neo4j_loader(parquet_object_name: str):
    """
    Runs the Neo4j loading job:
    1. Downloads the specified Parquet file from MinIO 'datasets' bucket.
    2. Transforms the records into Cypher-friendly batches.
    3. Executes batched MERGE queries to populate the Knowledge Graph.
    """
    print(f"Starting Neo4j Loader for {parquet_object_name}...")
    
    # 1. Setup Connections
    store = MinioStore()
    neo4j_conn = get_neo4j_connection()
    
    temp_file_path = f"/tmp/{os.path.basename(parquet_object_name)}"
    
    try:
        # Download Parquet file
        print(f"Downloading {DATASET_BUCKET}/{parquet_object_name}...")
        if not store.download_file(DATASET_BUCKET, parquet_object_name, temp_file_path):
            print("CRITICAL: Failed to download Parquet file. Exiting loader.")
            return

        # Read Parquet using Polars
        df = pl.read_parquet(temp_file_path)
        
        # Prepare data for Cypher
        records = df.to_dicts()
        print(f"Read {len(records)} records from Parquet file.")
        
        # 3. Ingest in Batches
        for i in range(0, len(records), BATCH_SIZE):
            batch = records[i:i + BATCH_SIZE]
            
            # Convert datetime objects to ISO string for safe Cypher parameter passing
            # and ensure other fields are not None
            cleaned_batch = []
            for record in batch:
                if record['created_utc'] and isinstance(record['created_utc'], datetime):
                    record['created_utc'] = record['created_utc'].isoformat()
                
                # Ensure author is not None (Reddit API can return [deleted])
                if not record.get('author'):
                    record['author'] = '[deleted]'
                
                cleaned_batch.append(record)

            
            # Cypher Query (MERGE for idempotency)
            query = """
            UNWIND $batch AS record
            
            // 1. Create Subreddit Node
            MERGE (s:Subreddit {name: record.subreddit})
            ON CREATE SET s.created_at = datetime(), s.updated_at = datetime()
            ON MATCH SET s.updated_at = datetime()
            
            // 2. Create Person Node (Author)
            MERGE (p:Person {username: record.author})
            ON CREATE SET p.created_at = datetime(), p.updated_at = datetime()
            ON MATCH SET p.updated_at = datetime()
            
            // 3. Create Post Node
            MERGE (po:Post {id: record.id})
            ON CREATE SET 
                po.created_utc = datetime({epochMillis: apoc.date.parse(record.created_utc, "ms", "yyyy-MM-dd'T'HH:mm:ss")}),
                po.title = record.title,
                po.selftext = record.selftext,
                po.score = record.score,
                po.upvote_ratio = record.upvote_ratio,
                po.url = record.url,
                po.source = 'reddit',
                po.updated_at = datetime()
            ON MATCH SET
                po.title = record.title,
                po.selftext = record.selftext,
                po.score = record.score,
                po.upvote_ratio = record.upvote_ratio,
                po.url = record.url,
                po.updated_at = datetime()

            // 4. Create Relationships
            MERGE (p)-[:POSTED {created_at: po.created_utc}]->(po)
            MERGE (po)-[:IN_SUBREDDIT {created_at: po.created_utc}]->(s)
            
            RETURN count(po) AS count
            """
            
            # Execute Write
            neo4j_conn.execute_write(query, parameters={"batch": cleaned_batch}, database=NEO4J_DATABASE)
            print(f"  -> Ingested batch {i//BATCH_SIZE + 1} of {len(records)//BATCH_SIZE + 1}")

        print("Successfully loaded all data into Neo4j.")

    except Exception as e:
        print(f"An error occurred during Neo4j ingestion: {e}")
    finally:
        # Cleanup
        if os.path.exists(temp_file_path):
            os.remove(temp_file_path)
        neo4j_conn.close()
        print("Neo4j Loader Finished.")


if __name__ == "__main__":
    # Example usage (assumes a Parquet file named 'weekly_archive_2024_42.parquet' exists in MinIO 'datasets' bucket)
    # The actual name will be generated by the ETL job
    # For a test, we will use a dummy name.
    
    # NOTE: You must run the weekly_archive.py first to generate the file.
    # For demonstration, we assume the file name.
    
    # We will need to decide on a file name convention. Let's use the current week/year.
    week_str = datetime.now().strftime('%Y_%W')
    example_filename = f"datasets/reddit/weekly_archive_{week_str}.parquet"
    
    print("WARNING: This script will fail if the Parquet file has not been generated by weekly_archive.py.")
    # For deployment, we assume the previous step (weekly_archive) generates a path and passes it here.
    # Since we are writing the module structure, we will use the assumed path.
    # The ETL job saves to: datasets/reddit/weekly_archive_{end_date.strftime('%Y_%W')}.parquet
    
    run_neo4j_loader(f"reddit/weekly_archive_{week_str}.parquet")
