#!/usr/bin/env python3
"""
Dashboard Generator for Universal Feed Reader.
Creates a static index.html file to browse downloaded articles.
"""

import os
import json
from pathlib import Path
from datetime import datetime
import re

DOWNLOAD_DIR = "reader_library"
DASHBOARD_FILE = "index.html"

DASHBOARD_TEMPLATE = """
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>My Feed Reader</title>
    <style>
        :root {{
            --primary: #2c3e50;
            --accent: #3498db;
            --bg: #f5f7fa;
            --card-bg: #ffffff;
            --text: #333;
            --text-light: #7f8c8d;
        }}
        body {{
            font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Helvetica, Arial, sans-serif;
            background-color: var(--bg);
            color: var(--text);
            margin: 0;
            padding: 0;
            line-height: 1.5;
        }}
        .container {{
            max-width: 900px;
            margin: 0 auto;
            padding: 40px 20px;
        }}
        header {{
            margin-bottom: 40px;
            border-bottom: 2px solid #eee;
            padding-bottom: 20px;
            display: flex;
            justify-content: space-between;
            align-items: center;
        }}
        h1 {{
            color: var(--primary);
            margin: 0;
            font-size: 2rem;
        }}
        .update-time {{
            color: var(--text-light);
            font-size: 0.9rem;
        }}
        .feed-section {{
            margin-bottom: 40px;
        }}
        .feed-title {{
            font-size: 1.4rem;
            color: var(--primary);
            margin-bottom: 15px;
            padding-left: 10px;
            border-left: 4px solid var(--accent);
        }}
        .article-grid {{
            display: grid;
            gap: 15px;
        }}
        .article-card {{
            background: var(--card-bg);
            padding: 20px;
            border-radius: 8px;
            box-shadow: 0 1px 3px rgba(0,0,0,0.05);
            transition: transform 0.2s, box-shadow 0.2s;
            text-decoration: none;
            color: inherit;
            display: block;
        }}
        .article-card:hover {{
            transform: translateY(-2px);
            box-shadow: 0 4px 6px rgba(0,0,0,0.1);
        }}
        .article-title {{
            font-size: 1.1rem;
            font-weight: 600;
            margin-bottom: 8px;
            color: var(--primary);
        }}
        .article-meta {{
            font-size: 0.85rem;
            color: var(--text-light);
            display: flex;
            justify-content: space-between;
        }}
        .empty-state {{
            text-align: center;
            padding: 40px;
            color: var(--text-light);
            font-style: italic;
        }}
    </style>
</head>
<body>
    <div class="container">
        <header>
            <h1>My Feed Reader</h1>
            <span class="update-time">Last updated: {generated_at}</span>
        </header>

        {content}

        <footer>
            <p style="text-align: center; color: #999; font-size: 0.8rem; margin-top: 50px;">
                Generated by Universal Feed Reader
            </p>
        </footer>
    </div>
</body>
</html>
"""

def prettify_name(slug):
    """Convert slug-like-name to Title Case."""
    return slug.replace('-', ' ').title()

def generate_dashboard():
    root_dir = Path(DOWNLOAD_DIR)
    if not root_dir.exists():
        print(f"Directory {DOWNLOAD_DIR} not found. Run the fetcher first.")
        return

    # Collect content
    feeds_data = {} # {feed_name: [articles]}

    # Scan directories
    for feed_dir in root_dir.iterdir():
        if feed_dir.is_dir():
            feed_name = prettify_name(feed_dir.name)
            articles = []
            
            for article_file in feed_dir.glob("*.html"):
                # Parse date from filename YYYY-MM-DD-slug.html
                match = re.match(r"(\d{4}-\d{2}-\d{2})-(.*)\.html", article_file.name)
                if match:
                    date_str = match.group(1)
                    slug = match.group(2)
                    title = prettify_name(slug)
                    
                    # Try to read actual title from HTML file for better accuracy
                    try:
                        with open(article_file, 'r', encoding='utf-8') as f:
                            content = f.read(1000) # Read start
                            title_match = re.search(r"<title>(.*?)</title>", content)
                            if title_match:
                                title = title_match.group(1)
                    except:
                        pass

                    articles.append({
                        'title': title,
                        'date': date_str,
                        'path': f"{feed_dir.name}/{article_file.name}",
                        'timestamp': datetime.strptime(date_str, "%Y-%m-%d")
                    })
            
            # Sort articles by date descending
            articles.sort(key=lambda x: x['timestamp'], reverse=True)
            feeds_data[feed_name] = articles

    # Generate HTML Content
    html_sections = ""
    
    if not feeds_data:
        html_sections = '<div class="empty-state">No articles found. Run the fetcher to download content.</div>'
    
    # Sort feeds by name
    sorted_feeds = sorted(feeds_data.items())

    for feed_name, articles in sorted_feeds:
        if not articles:
            continue
            
        section_html = f'<div class="feed-section"><h2 class="feed-title">{feed_name}</h2><div class="article-grid">'
        
        for article in articles:
            # Format date nicer
            display_date = article['timestamp'].strftime("%b %d, %Y")
            
            section_html += f"""
            <a href="{article['path']}" class="article-card">
                <div class="article-title">{article['title']}</div>
                <div class="article-meta">
                    <span>{display_date}</span>
                </div>
            </a>
            """
        
        section_html += "</div></div>"
        html_sections += section_html

    # Final HTML
    final_html = DASHBOARD_TEMPLATE.format(
        generated_at=datetime.now().strftime("%Y-%m-%d %H:%M"),
        content=html_sections
    )

    output_path = root_dir / DASHBOARD_FILE
    with open(output_path, 'w', encoding='utf-8') as f:
        f.write(final_html)

    print(f"✅ Dashboard generated: {output_path}")

if __name__ == "__main__":
    generate_dashboard()
